In [1]:
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.model_selection import train_test_split
from IPython.display import display
from IPython.display import Image
from sklearn.externals.six import StringIO  
from sklearn.tree import export_graphviz
from sklearn.linear_model import LogisticRegression
import pydot
pd.options.display.max_columns = None


In [2]:
# import dta
X = pd.read_csv('FinancialMetrics.csv')
y = pd.read_csv('DPD90.csv')

# split training data, validation data and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=102)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=102)

AdaBoost Classifier

In [3]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), algorithm="SAMME", n_estimators=200)
bdt.fit(X_train, y_train)
bdt_val = bdt.predict(X_val)
val_prob_bdt = bdt.predict_proba(X_val)
bdt_pred = bdt.predict(X_test)
pred_prob_bdt = bdt.predict_proba(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,bdt_pred))
print(classification_report(y_test,bdt_pred))

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[1536  176]
 [ 183 1105]]
              precision    recall  f1-score   support

           0       0.89      0.90      0.90      1712
           1       0.86      0.86      0.86      1288

   micro avg       0.88      0.88      0.88      3000
   macro avg       0.88      0.88      0.88      3000
weighted avg       0.88      0.88      0.88      3000



Random Forest Classifier

In [4]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier() #
rfc.fit(X_train, y_train)
rfc_val = rfc.predict(X_val)
val_prob_rfc = rfc.predict_proba(X_val)
rfc_pred = rfc.predict(X_test)
pred_prob_rfc = rfc.predict_proba(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,rfc_pred))
print(classification_report(y_test,rfc_pred))

[[1579  133]
 [ 223 1065]]
              precision    recall  f1-score   support

           0       0.88      0.92      0.90      1712
           1       0.89      0.83      0.86      1288

   micro avg       0.88      0.88      0.88      3000
   macro avg       0.88      0.87      0.88      3000
weighted avg       0.88      0.88      0.88      3000



D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Random Forest CrossValidation

In [5]:
from sklearn.model_selection import GridSearchCV
rfc = RandomForestClassifier() 

param_grid = {'min_samples_leaf': [2, 4, 6], 
              'max_depth': [3, 6, 9, 12], 
              'min_samples_split': [2, 5, 10]}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid)
CV_rfc.fit(X_train, y_train)
CV_rfc_val = CV_rfc.predict(X_val)
val_prob_CV_rfc = CV_rfc.predict_proba(X_val)
CV_rfc_pred = CV_rfc.predict(X_test)
pred_prob_CV_rfc = CV_rfc.predict_proba(X_test)

print(confusion_matrix(y_test,CV_rfc_pred))
print(classification_report(y_test,CV_rfc_pred))

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\si

D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Ana

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Ana

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Ana

D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Ana

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Ana

[[1551  161]
 [ 171 1117]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90      1712
           1       0.87      0.87      0.87      1288

   micro avg       0.89      0.89      0.89      3000
   macro avg       0.89      0.89      0.89      3000
weighted avg       0.89      0.89      0.89      3000



D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:740: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


Support Vector Classifier

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
scaled_X = scaler.transform(X)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [7]:
# X_train, X_test, y_train, y_test = train_test_split(scaled_X,y, test_size=0.30, random_state=101)
X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.3, random_state=102)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=102)

In [8]:
from sklearn.svm import SVC
svc = SVC(probability=True)
svc.fit(X_train,y_train)
svc_val = svc.predict(X_val)
val_prob_svc = svc.predict_proba(X_val)
svc_pred = svc.predict(X_test)
pred_prob_svc = svc.predict_proba(X_test)

svc_trainpred = pd.DataFrame(svc.predict(X_train))
svc_testpred = pd.DataFrame(svc.predict(X_test))

print(confusion_matrix(y_test,svc_pred))
print(classification_report(y_test,svc_pred))

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[[1579  133]
 [ 173 1115]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91      1712
           1       0.89      0.87      0.88      1288

   micro avg       0.90      0.90      0.90      3000
   macro avg       0.90      0.89      0.90      3000
weighted avg       0.90      0.90      0.90      3000



k-Nearest Neigbors Classifier

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train,y_train)
knn_val = knn.predict(X_val)
val_prob_knn = knn.predict_proba(X_val)
knn_pred = knn.predict(X_test)
pred_prob_knn = knn.predict_proba(X_test)

print(confusion_matrix(y_test,knn_pred))
print(classification_report(y_test,knn_pred))

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[[1519  193]
 [ 189 1099]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89      1712
           1       0.85      0.85      0.85      1288

   micro avg       0.87      0.87      0.87      3000
   macro avg       0.87      0.87      0.87      3000
weighted avg       0.87      0.87      0.87      3000



Stacking Ensemble Using Logistic Regression

In [11]:
ens_val = pd.concat([pd.DataFrame(val_prob_rfc[:,1]), 
                     pd.DataFrame(val_prob_svc[:,1]), 
                     pd.DataFrame(val_prob_bdt[:,1])], axis=1)
ens_test = pd.concat([pd.DataFrame(pred_prob_rfc[:,1]), 
                      pd.DataFrame(pred_prob_svc[:,1]), 
                      pd.DataFrame(pred_prob_bdt[:,1])],axis=1)

lrc = LogisticRegression()
lrc.fit(ens_val, y_val)
lrc_pred = lrc.predict(ens_test)
lrc_val_pred = lrc.predict(ens_val)

val_prob_lrc = lrc.predict_proba(ens_val)
pred_prob_lrc = lrc.predict_proba(ens_test)

lrc_valpred = pd.DataFrame(val_prob_lrc)
lrc_testpred = pd.DataFrame(pred_prob_lrc)

print(confusion_matrix(y_test,lrc_pred))
print(classification_report(y_test,lrc_pred))

[[1583  129]
 [ 180 1108]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91      1712
           1       0.90      0.86      0.88      1288

   micro avg       0.90      0.90      0.90      3000
   macro avg       0.90      0.89      0.89      3000
weighted avg       0.90      0.90      0.90      3000



D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
